services:
  db:
    image: mysql:8.0
    container_name: lab7_xo_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: lab7_xo
    ports:
      - "3306:3306"
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - lab7_xo_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  lab7_xo_data:
